title       : "ESD R TOOLBOX"
subtitle    : "by MET Norway" 
description : "ESD R Tool for visualising and downscaling climate data"

logo        : "/assets/images/Met_RGB_Horisontal_ENG.jpeg"

# Build settings
markdown: kramdown
# remote_theme: pmarsceill/just-the-docs
remote_theme: "mmistakes/minimal-mistakes@4.19.0"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "pages"
      mathjax: true

search: true

# Reading Files
include:
  - _pages

## Additional plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache